FROM python:3.10-slim


RUN apt-get update && apt-get install -y 

WORKDIR /app
COPY . /app

RUN pip install --upgrade pip && pip install -r requirements.txt

EXPOSE 5179

CMD ["python", "-u", "api.py"]
